name: Branch Protection

on:
  push:
    branches:
      - master
      - develop

jobs:
  protect-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
          cache: true

      # 3. Ahora sí puedes ejecutar comandos de Flutter
      - name: Install dependencies
        run: flutter pub get

      # 4. Agrega aquí otros comandos que necesites
      - name: Run tests
        run: flutter test